import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./Component2/Menu/Menu";
import Footer from './Component2/Footer/page';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DineSmart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menu/>
        
        {children}
      </body>
    </html>
  );
}
