import "./globals.css";
import Menu from "./Component2/Menu/Menu";
import Footer from './Component2/Footer/page';




export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menu/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
