import "./globals.css";
import Menu from "./Component/Menu/Menu";
import Footer from './Component/Footer/page';




export async function generateMetadata() {
  return {
    title: "Home",
    description: "Generated by create next app",
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menu/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
